const app = new Vue({
    el: ".main-content",
    data: {
        // frontTr: "rotateY(0deg)",
        // backTr: "rotateY(180deg)",

        datas: [
            {
                title: "West Semifinals-Series GSW Lead 3-2",
                t1_posi: "WC-4",
                t1_pic: "https://mat1.gtimg.com/sports/nba/logo/1602/10.png",
                t2_posi: "WC-1",
                t2_pic: "https://mat1.gtimg.com/sports/nba/logo/1602/9.png",
                game: "GAME 5",
                time: "9:00",
                date: "11 May 2019",
                game_time: "may 11,2019 9:00:00",
                team1: "Houston Rockets",
                t1_arena: "Toyota Center",
                t1_division: "西南区",
                t1_rank: "西区第四、分区第一",
                t1_coach: "Mike D'Antoni",
                t1_player: "James Harden",
                t1_p1_pic:
                    "https://nba.sports.qq.com/media/img/players/head/260x190/201935.png",
                t1_p1_pts: "36.1",
                t1_p1_reb: "6.6",
                t1_p1_ast: "7.5",
                team2: "Golden State Warriors",
                t2_arena: "Oracle Arena",
                t2_division: "太平洋区",
                t2_rank: "西区第一、分区第一",
                t2_coach: "Steve Kerr",
                t2_player: "Kevin Durant",
                t2_p2_pic:
                    "https://nba.sports.qq.com/media/img/players/head/260x190/201142.png",
                t2_p2_pts: "36.1",
                t2_p2_reb: "6.6",
                t2_p2_ast: "7.5"
            },
            {
                title: "West Semifinals-Series Tied 2-2",
                t1_posi: "WC-2",
                t1_pic: "http://mat1.gtimg.com/sports/nba/logo/1602/20187.png",
                t2_posi: "WC-3",
                t2_pic: "https://mat1.gtimg.com/sports/nba/logo/new/22.png",
                game: "GAME 6",
                time: "10:30",
                date: "10 May 2019",
                game_time: "may 10,2019 10:30:00",
                team1: "Denver Nuggets",
                t1_arena: "Pepsi Center",
                t1_division: "西北区",
                t1_rank: "西区第二、分区第一",
                t1_coach: "Michael Malone",
                t1_player: "Nikola Jokic",
                t1_p1_pic:
                    "https://nba.sports.qq.com/media/img/players/head/260x190/203999.png",
                t1_p1_pts: "36.1",
                t1_p1_reb: "6.6",
                t1_p1_ast: "7.5",
                team2: "Portland Trail Blazers",
                t2_arena: "Moda Center",
                t2_division: "西北区",
                t2_rank: "西区第三、分区第二",
                t2_coach: "Terry Stotts",
                t2_player: "Damian Lillard",
                t2_p2_pic:
                    "https://nba.sports.qq.com/media/img/players/head/260x190/203081.png",
                t2_p2_pts: "36.1",
                t2_p2_reb: "6.6",
                t2_p2_ast: "7.5"
            },
            {
                title: "East Semifinals-Series MIL 4-1 Advance",
                t1_posi: "EC-1",
                t1_pic: "https://mat1.gtimg.com/sports/nba/logo/1602/15.png",
                t2_posi: "EC-4",
                t2_pic: "https://mat1.gtimg.com/sports/nba/logo/1602/2.png",
                game: "GAME 5",
                time: "8:00",
                date: "09 May 2019",
                game_time: "may 09,2019 08:00:00",
                team1: "Milwaukee Bucks",
                t1_arena: "BMO Harris Bradley Center",
                t1_division: "中部区",
                t1_rank: "东区第一、分区第一",
                t1_coach: "Mike Budenholzer",
                t1_player: "Giannis Antetokounmpo",
                t1_p1_pic:
                    "https://nba.sports.qq.com/media/img/players/head/260x190/203507.png",
                t1_p1_pts: "36.1",
                t1_p1_reb: "6.6",
                t1_p1_ast: "7.5",
                team2: "Boston Celtics",
                t2_arena: "TD Garden",
                t2_division: "大西洋区",
                t2_rank: "东区第四、分区第三",
                t2_coach: "Brad Stevens",
                t2_player: "Kyrie Irving",
                t2_p2_pic:
                    "https://nba.sports.qq.com/media/img/players/head/260x190/202681.png",
                t2_p2_pts: "36.1",
                t2_p2_reb: "6.6",
                t2_p2_ast: "7.5"
            },
            {
                title: "East Semifinals-Series Tied 2-2",
                t1_posi: "EC-2",
                t1_pic:
                    "https://img1.gtimg.com/sports/pics/hv1/133/21/2268/147482188.png",
                t2_posi: "EC-3",
                t2_pic: "https://mat1.gtimg.com/sports/nba/logo/1602/20.png",
                game: "GAME 6",
                time: "8:00",
                date: "10 May 2019",
                game_time: "may 10,2019 08:00:00",
                team1: "Toronto Raptors",
                t1_arena: "Air Canada Centre",
                t1_division: "大西洋区",
                t1_rank: "东区第二、分区第一",
                t1_coach: "Nick Nurse",
                t1_player: "Kawhi Leonard",
                t1_p1_pic:
                    "https://nba.sports.qq.com/media/img/players/head/260x190/202695.png",
                t1_p1_pts: "36.1",
                t1_p1_reb: "6.6",
                t1_p1_ast: "7.5",
                team2: "Philadelphia 76ers",
                t2_arena: "Wells Fargo Center",
                t2_division: "大西洋区",
                t2_rank: "东区第三、分区第四",
                t2_coach: "Brett Brown",
                t2_player: "Joel Embiid",
                t2_p2_pic:
                    "http://mat1.gtimg.com/sports/NBAImages/PlayerImages/260x190203954.png",
                t2_p2_pts: "36.1",
                t2_p2_reb: "6.6",
                t2_p2_ast: "7.5"
            }
        ]
    },
    methods: {}
});
